### ISSUE TITLE
Инпуты

### ISSUE THREAD

**Issue by Yubil-Olga** [MetalHead89/fsd_part2#10]
Проверь, чтобы у всех инпутов был установлен type.
Также любой кликабельный элемент должен иметь cursior: pointer

**Comment by OlgaYubil** [comment]
У всех инпутов должен быть указан правильный type: text, password и т.д.

**Comment by OlgaYubil** [comment]
Парочку инпутов пропустил)

**Comment by OlgaYubil** [comment]
Можно закрыть
