### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by Yubil-Olga** [MetalHead89/fsd_part2#11]
Чтобы не добавлять каждый раз new HTMLWebpackPlugin, можно вынести его создание в функцию
![2021-04-12_10-51-28](https://user-images.githubusercontent.com/47268368/114360246-7c168500-9b7d-11eb-82d6-f11feeb97980.png)

**Comment by OlgaYubil** [comment]
Это не совсем то, что я хотела бы увидеть.  Ты вынес информацию по страничкам в отдельный json-файл, а было бы здорово динамически находить все файлы с расширением .pug и генерировать их в html.

**Comment by OlgaYubil** [comment]
У меня сейчас не собирается твой проект, ни dev, ни build. Кстати, какая у тебя версия node.js? Укажи в файле readme совместимую версию

**Comment by OlgaYubil** [comment]
В папке dist файлы как-то все вперемешку. Шрифты, картинки и в assets, и в разнобой лежат.
