### ISSUE TITLE
Параметры миксина

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part2#16]
Объект можно деструктурировать сразу в параметрах, например:
```
mixin bullet-list({ menuItems, theme} = {})
```

Кроме того, параметры необходимо валидировать перед тем, как использовать. Здесь, например, неочевидно какие параметры мы можем передать в качестве темы.

![2021-05-10_23-23-16](https://user-images.githubusercontent.com/82147736/117726789-bfe9c200-b1ef-11eb-8967-5aa6b110cbfa.png)

**Comment by OlgaYubil** [comment]
Параметры миксина можно передать так: 
```mixin navbar({ type = 'horizontal', items, } = {})```
И поправь, пожалуйста, пробелы.
В данном случае совсем неочевидно, какие варианты темы, кроме горизонтальной, можно выбрать

![2021-06-01_23-40-07](https://user-images.githubusercontent.com/82147736/120445096-f2bb4c00-c390-11eb-9b9c-09001aa524a7.png)

**Comment by MetalHead89** [comment]
Изменены параметры миксинов с использованием значений по-умочанию, поправлены пробелы, добавлена валидация параметра type в миксине компонента navbar

**Comment by OlgaYubil** [comment]
Тэг никак не валидируется

![2021-06-11_15-19-03](https://user-images.githubusercontent.com/82147736/121685338-7a5b3600-cac8-11eb-8766-37928aba6ae2.png)

**Comment by MetalHead89** [comment]
Валидирован параметр tag модуля type-block
