### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part2#17]
Здесь можно избежать дублирования

![2021-05-10_23-37-47](https://user-images.githubusercontent.com/82147736/117727153-5322f780-b1f0-11eb-867c-3f953d465177.png)

![2021-05-10_23-40-58](https://user-images.githubusercontent.com/82147736/117727162-57e7ab80-b1f0-11eb-9a29-c5a13dfb9615.png)

![2021-05-10_23-45-14](https://user-images.githubusercontent.com/82147736/117727195-6209aa00-b1f0-11eb-9b35-7c7a445fb65f.png)

**Comment by OlgaYubil** [comment]
Зачем делать значение модификатора not-transparent? Можно использовать булевый модификатор.

![2021-06-11_14-17-08](https://user-images.githubusercontent.com/82147736/121683565-39fab880-cac6-11eb-91f1-98a8dd0a2ec1.png)

**Comment by OlgaYubil** [comment]
В данном примере всего два возможных значения(вертикальный/горизонтальный), тоже можно заменить булевым модификатором. Но если хочется оставить возможность к расширению компонента, то лучше обойтись без мутации параметра, например ввести переменную typeModifier

![2021-06-11_14-40-11](https://user-images.githubusercontent.com/82147736/121683973-c3aa8600-cac6-11eb-9bd1-c2b9cf9ff11c.png)

**Comment by MetalHead89** [comment]
Удалено значение модификатора not-transparent в модуле room-card. В модуле navbar введена переменная typeModifier для исключения мутации параметра type

**Comment by OlgaYubil** [comment]
Аналогично как и transparent

![2021-06-16_17-08-40](https://user-images.githubusercontent.com/82147736/122237595-1e2d5300-cec8-11eb-9704-bc9e9e0a485b.png)

**Comment by OlgaYubil** [comment]
В navbar стоит как-то по-другому организовать переключение состояния. У элемента hidden-list сейчас имеется 3 булева модификатора: vertical, vertical-opened, vertical-closed.

![2021-06-28_22-46-05](https://user-images.githubusercontent.com/82147736/123697164-42444900-d865-11eb-80eb-1777f1135374.png)

**Comment by OlgaYubil** [comment]
![2021-06-28_22-37-49](https://user-images.githubusercontent.com/82147736/123697694-df9f7d00-d865-11eb-8e09-c9474bd040f0.png)

**Comment by OlgaYubil** [comment]
Можно обойтись без такого количества дополнительных классов, вполне достаточно знать, что корневой элемент vertical (а вложенные в него будут вести себя соответствующим образом)

![2021-07-07_23-37-30](https://user-images.githubusercontent.com/82147736/124826791-f046a600-df7d-11eb-9afa-b21074236db6.png)
