### ISSUE TITLE
Миксы

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part2#18]
По стандартам миксы не используем https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.6

![2021-05-10_23-43-33](https://user-images.githubusercontent.com/82147736/117727648-fd9b1a80-b1f0-11eb-8b27-230a5076d406.png)

**Comment by OlgaYubil** [comment]
Вот еще микс

![2021-06-01_15-17-02](https://user-images.githubusercontent.com/82147736/120442367-32ccff80-c38e-11eb-834c-cb360bebf971.png)

**Comment by OlgaYubil** [comment]
![2021-06-01_23-34-23](https://user-images.githubusercontent.com/82147736/120444700-89d3d400-c390-11eb-8ea0-21159356b513.png)

**Comment by MetalHead89** [comment]
Переработан код с миксами, удален класс material-icons у модулей, элементы __column-one, __column-two и __column-three переделаны в модификаторы _first-column, _second-column и _third-column соответственно
