### ISSUE TITLE
Impressions diagram

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part2#28]
У меня и в dev, и в build сборках вот так выглядит

![2021-07-07_22-56-24](https://user-images.githubusercontent.com/82147736/124829115-d8245600-df80-11eb-99ba-7e68dadb6f60.png)

**Comment by MetalHead89** [comment]
Переделан блок impressions-diagram, теперь диаграмма корректо отображается в dev и build сборках
