### ISSUE TITLE
Посторонние классы в стилях

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part2#29]
![2021-07-28_19-06-09](https://user-images.githubusercontent.com/82147736/127360320-738e42f6-8d19-4932-b01a-0df9cbc32aa3.png)

**Comment by OlgaYubil** [comment]
UI-kit и page-with-links тоже нужно привести в порядок в соответствии со стандартами

![2021-07-30_17-10-36](https://user-images.githubusercontent.com/82147736/127665667-c779954e-3ec2-4554-8b69-1b37639cdeb4.png)

**Comment by MetalHead89** [comment]
Страницы page-with-links и ui-kit переделаны в соответствии со стандартами
