### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by OlgaYubil** [MetalHead89/fsd_part2#31]
Зачем искать дочерние элементы, когда обработчик можно повесить и на js-dropdown__button-clear?

![2021-07-30_16-45-47](https://user-images.githubusercontent.com/82147736/127666208-3aad5fa7-175f-4285-9d31-a2532d90a59f.png)

**Comment by OlgaYubil** [comment]
В классе Dropdown содержится слишком много настроек для разных типов дропдаунов. Нужно сделать его более универсальным (например, для кнопки apply неважно какой тип реализуется, она выполняет конкретное действие). Стоит разбить этот класс на несколько сущностей, которые будут, например, наследоваться от базового класса Dropdown. 

![2021-07-30_16-54-25](https://user-images.githubusercontent.com/82147736/127666453-c5e8a59e-b10f-48ac-be34-c2a98f24d706.png)

**Comment by OlgaYubil** [comment]
Это все разные компоненты, они должны быть максимально самодостаточны, чтобы их было удобно переиспользовать. Аналогично как и во всем проекте, один компонент - отдельная папка, pug-файл... 

![2021-08-06_00-29-46](https://user-images.githubusercontent.com/82147736/128423873-83369e9f-320e-4be5-804f-bfafdf8f9391.png)

**Comment by OlgaYubil** [comment]
Для чего нужно делать два разных класса start-day-input и end-day-input? Стили у них одинаковые, функционал тоже.

![2021-08-12_23-03-56](https://user-images.githubusercontent.com/82147736/129264182-631bb177-09d1-4d28-b670-5c41d7249460.png)

**Comment by MetalHead89** [comment]
Удалены классы date-dropdown__start-date-input и date-dropdown__end-date-input, оставлен один общий класс  date-dropdown__input. Полностью переделаны дропдауны, добавлены дополнительные блоки.

**Comment by OlgaYubil** [comment]
Когда нажимаем на кнопку очистить, не убирается активный стиль с "-" и можно задать отрицательное значение.

![GIF 30 08 2021 21-40-10](https://user-images.githubusercontent.com/82147736/131391613-e8739687-6599-455b-b436-686d9446fe8c.gif)
