### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Yubil-Olga** [MetalHead89/fsd_part2#7]
Поправить пробелы (один уровень — 2 пробела)

**Comment by OlgaYubil** [comment]
В scss очень удобно обращаться к имени блока через &. Вот так:
![2021-04-19_00-45-18](https://user-images.githubusercontent.com/82147736/115161856-9df59780-a0a8-11eb-90f4-f44e5de6caaf.png)
Исправь у себя, чтобы было в таком же стиле

**Comment by OlgaYubil** [comment]
Не все исправил
![2021-04-30_11-00-09](https://user-images.githubusercontent.com/82147736/116670096-00536f80-a9a8-11eb-9551-055882adcf58.png)

![2021-04-30_11-07-10](https://user-images.githubusercontent.com/82147736/116669979-e4e86480-a9a7-11eb-8ece-14153fd68504.png)

**Comment by OlgaYubil** [comment]
Для layout должен быть только pug-файл, а все стили находятся в папках соответствующих компонентов
![2021-04-30_11-19-13](https://user-images.githubusercontent.com/82147736/116670312-3db7fd00-a9a8-11eb-93b8-26e49efad4b9.png)

**Comment by OlgaYubil** [comment]
keyframes лучше будет вынести в отдельный файл _animations.scss

**Comment by OlgaYubil** [comment]
Я имела ввиду создать в папке scss один файл для всех анимаций, как сделано для миксинов.

**Comment by OlgaYubil** [comment]
![2021-05-10_23-31-59](https://user-images.githubusercontent.com/82147736/117727815-32a76d00-b1f1-11eb-99ae-5207493988b0.png)

**Comment by OlgaYubil** [comment]
Можно закрыть
